### ISSUE TITLE
Nettside med patching

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#11]
Vi lager en nettside hvor man kan laste opp ROM og få den patchet til norsk

**Comment by grenasberg** [comment]
en enkel side med en kul interface hvor du kan dragge og droppe en rom og så får du en norsk rom tilbake

skal vi også ha utviklerbloggen på siden hvor vi skriver om prosessen?

**Comment by tobiasvl** [comment]
@grenasberg last opp mockupen din her

ja til blogg (blir vel ikke så mange blogginnlegg kanskje men interessant å skrive om valgene vi har tatt)

**Comment by grenasberg** [comment]
upload rom mockup:
https://user-images.githubusercontent.com/6959974/198112794-ee052c26-cbdd-4f7e-b8a0-d0c86682359e.mp4

**Comment by tobiasvl** [comment]
Kan baseres på:
* https://www.marcrobledo.com/RomPatcher.js/
* https://github.com/bbbradsmith/ipstool

Tanker:
* Vi bør lage flere patch-filer, én for hver versjon av ROM-en (1.0, 1.1, 1.2, USA/EUR, tysk, osv) så det ikke spiller noen rolle hvilken man har (det er irriterende når man MÅ patche USA 1.0 f. eks.). Patch velges sømløst basert på utgangs-ROM, bruker trenger ikke tenke på det
* Og da kan den første labelen i animasjonen reflektere hvilken ROM som ble lastet opp (gullbakgrunn for USA f. eks.)
* Labelen til Links oppvåkning bør ha kode DMG-AZLN-SCN som diskutert på messenger

**Comment by tobiasvl** [comment]
https://vindfisken.no
