### ISSUE TITLE
Fysiske carts

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#18]
https://bbbbbr.github.io/GameBoy-Flash-Carts/

## Flasher

Vi må kunne flashe ROM-en på carten. GBxCart ser bra ut:

- https://shop.insidegadgets.com/product/gbxcart-rw/
- https://www.zedlabz.com/products/gbxcart-rw-1-4-pro-reader-writer-flasher-for-gameboy-color-advance-cart-usb-c-game-cartridge-backup-adapter-gb-gba-gbc-insidegadgets (samme men fra Europa, dyr)

## PCB

Vi trenger:
- MBC5
- 32 kB RAM

Jeg har funnet denne:
- https://shop.insidegadgets.com/product/gameboy-2mb-32kb-fram-flash-cart-ultra-low-power/
- https://www.zedlabz.com/products/flash-cart-for-nintendo-gameboy-2mb-32kb-fram-ultra-low-power-insidegadgets (samme men fra Europa, dyr)

Er det et alternativ å reflashe billige repro carts? 
https://flashcartdb.com/index.php/Main_Page#GameBoy_Clone.2FRepro_Flash_Carts
eller da må vi kanskje ha batteryless patch og en del styr

Her kan vi få både pcb, label og shell (ikke gull da): 
https://www.etsy.com/listing/1254312880/premium-2mb-gbgbc-flash-cart-32kb-fram her kan vi få alt i en pakke
(men vi vil jo ikke ha pre-applied label på et shell vi ikke skal bruke ...)

## Shell

Vi skal vel ha guld?

Her er det 2 stk inne, kan jo hende det restockes, men si fra om dere finner andre:

- https://shop.insidegadgets.com/product/dmg-high-quality-reproduction-cartridge-shell/
Aliexpress har samme ser det ut til:
- https://www.aliexpress.com/item/1005005023842482.html

## Label

Etsy-folk lager custom labels:

- https://www.etsy.com/no-en/listing/742421178/gbc-custom-replacement-label-decal?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=gameboy+game+label&ref=sr_gallery-2-12&organic_search_click=1
- https://www.etsy.com/no-en/listing/1411423593/game-boy-game-boy-color-label-cartridge?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=gameboy+game+label&ref=sr_gallery-1-24&organic_search_click=1&variation0=3253595359
- https://www.etsy.com/no-en/listing/1319688354/game-replacement-labels-pick-one-for-n64?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=gameboy+game+label&ref=sr_gallery-2-24&organic_search_click=1&variation0=3247915463

**Comment by grenasberg** [comment]
custom box og https://www.etsy.com/de-en/listing/689261347/gameboy-color-custom-boxes-ask-before ? og inner tray https://www.etsy.com/de-en/listing/1026278246/nintendo-gameboy-color-inlay-insert

**Comment by grenasberg** [comment]
har testa at flashing av repro med batteri fungerer, så har bestilt en del flere nå. 
mål:
lage 3 chrome gull-carts til de tre oversetterne med manual, boks og det hele
og noen ekstra cart only i kjedeligere gull til å låne bort etc.

**Comment by juliusvl** [comment]
Etter å ha sett litt på noen av GB-cartsene mine syns jeg det ser ut som de er printa vanlig, ikke med noen fancy effekter eller gull på Seal of Qualty-merket, som jeg først trudde. Hvis vi vil ha «ekte» look syns jeg vi bør gå for vanlig blankt (bestrøket) papir. 

Men dette kan vi så klart snakke om.
