### ISSUE TITLE
Legg til støtte for særnorske tegn

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#2]
Vi trenger ÆæØøÅå i fonten. Kanskje også norske fnutter, «». Noe annet?

* Legg til grafikk for disse
* Legg til støtte for dem i tekstfunksjonene

**Comment by tobiasvl** [comment]
Tegnene i tekstfilene mappes til tiles i to steg, så vi må endre tre steder:

1. Tegn i tekstfil -> «ASCII»:
   * Player name (#4): https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/constants/charmaps/name_entry.asm
   * Resten av spillet: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/constants/charmaps/ascii.asm
2. «ASCII» -> tile: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/data/ascii_to_tile.asm
3. Tilemap for player name (#4): https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/data/backgrounds/menu_file_creation.tilemap.encoded
4. Grafikk:
    * Credits: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/ending/credits_roll.png
    * Resten av spillet: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/fonts/font.cgb.png

Hvis vi vil ha Åå to tiles høye, må vi endre på:
1. Grafikk: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/revision/G0/src/gfx/items/inventory_overworld_items.cgb.png
2. Hvilke tegn som skal ha hvilken ekstra tile: https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/revision/G0/src/data/ascii_to_tile.asm (bare i tysk)
3. Og igjen passe på at https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/data/backgrounds/menu_file_creation.tilemap.encoded er riktig

**Comment by tobiasvl** [comment]
@juliusvl legg gjerne inn bilde av fontforslaget her, og si fra om du vil at Åå skal være to tiles høye som på tysk! Det går an å fikse.

![image](https://user-images.githubusercontent.com/80824/195916452-7b5b40d1-391f-46e3-8ae8-ea4599491f6a.png)

**Comment by tobiasvl** [comment]
Det eneste jeg ikke er 100 % sikker på nå er hvordan den mapper selve tegnet som skal være to tiles høy til bokstav og diakritisk tegn. Det skjer her, men skjønner ikke helt oppslaget i tabellen. https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/code/home/dialog.asm#L600

**Comment by tobiasvl** [comment]
Zelda bruker jo ellipser veldig mye ([et japansk fenomen](https://legendsoflocalization.com/qa-japanese-ellipsis-usage-and-english-translation/)).

På norsk skal man egentlig ha mellomrom foran ellipse [i følge Språkrådet](https://www.sprakradet.no/svardatabase/sporsmal-og-svar/utelatelsestegn-tre-punktum-med-eller-uten-mellomrom-foran/).

Burde vi legge til … som ett enkelt tegn, i stedet for å bruke opp tre hele tegn på å skrive ...? Da kan vi putte inn et mellomrom foran og likevel bare bruke to tegn på en ellipse, mot tre tegn på engelsk.

Spørsmålet er om det blir for sammentrykket, men jeg tror det kan funke.

I så fall har vi hittil disse særnorske tegnene som må legges til: ÆæØøÅå«»…

Si fra om dere har flere! Trenger vi f. eks. skille mellom bindestrek og tankestrek? https://www.sprakradet.no/sprakhjelp/Skriveregler/tegn/Tankestrek/

**Comment by grenasberg** [comment]
ja til enkelt tegn med ellipse. tenkte på det med mellomrom og at det ble for ekstravagant å sløse med plassen, men tenkte ikke på at vi kan lage et eget tegn for ellipse og dermed ha plass til et mellom før.

**Comment by tobiasvl** [comment]
Denne er vel ferdig
