### ISSUE TITLE
Gå gjennom alle dialogvalg

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#26]
Plasseringen til markøren når man velger mellom to svar i dialogene er hardkodet. Vi må:

- Gå gjennom alle dialoglinjer med `<ask>`
- Finn ut om vi kan skrive om alle disse til å passe med den hardkodede plasseringen

ELLER

- Gå gjennom alle dialoglinjer med `<ask>`
- Finne en god plassering av markørene som passer med majoriteten av disse linjene
- Eventuelt skrive om de som ikke funker med denne nye plasseringen
- Endre de hardkodede verdiene

**Comment by grenasberg** [comment]
markør står alltid på plass 4 og 9
```
   ⨀Look⨀Don't!
   ⨀Yes ⨀No 
```
```
   ⨀Kjøp⨀La være
   ⨀Ja  ⨀Nei 
```
Hvis vi går for 1 må vi altså passe på at valg 1 starter på plass 5 og valg 2 starter på plass 10

**Comment by tobiasvl** [comment]
@grenasberg kanskje du kan lage et skript som sjekker alle valg?

**Comment by grenasberg** [comment]
https://andreas.killie-grenasberg.no/zeldatools/ask/
Har laget en ask-sjekker

**Comment by grenasberg** [comment]
Vi må normalisere La være/La vær. Der har vi skrevet ulikt

**Comment by grenasberg** [comment]
Endret alle til La være
Sjekket og fikset alle linjer med <ask>
