### ISSUE TITLE
Valg i dialog

### ISSUE THREAD

**Issue by juliusvl** [koholition/zelda-links-awakening-NO#32]
Fikse dialog med valg til slutt, der det noen ganger lages blank linje med cursor i stedet for at cursor er på samme linje som teksten i på ASK-linja

**Comment by tobiasvl** [comment]
Eksempler: Dialog019, Dialog02B, Dialog030, Dialog032

**Comment by tobiasvl** [comment]
Dette kommer av en bug i originalspillet som jeg har dokumentert her: https://github.com/zladx/LADX-Disassembly/pull/539#issuecomment-1631204767
