### ISSUE TITLE
Fiks credits

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#33]
Bortsett fra at credits selvsagt må oversettes, er det et par problemer:

- [x] Tilesettet for de store bokstavene er forskjøvet litt av en eller annen grunn
- [x] Den siste meldingen, "The development team would like to thank you for playing", må fikses
- [x] Vi må inn i credits
- [x] Lage Ø i credits-fonten
- [x] Endre THE END til SLUTT

**Comment by grenasberg** [comment]
Og vi må inn i credits.

**Comment by juliusvl** [comment]
Og jeg må lage Ø i credits-bokstavene. Kan like gjerne lage Æ og Å når jeg er i gang, så lenge det er plass.

**Comment by grenasberg** [comment]
den enkleste leveransen og raskeste fixen vi kan gjøre på rulleteksten er:
bytte ut 
    db "  ENGLISH SCRIPT  "
til f.eks NORSK VERSJON
og de tre navnene
    db "   JIM WORNELL    "
    db "   KEIKO TAMURA   "
    db "    TAMAYO ITO    "
til våre navn
    db "TOBIAS V. LANGHOFF"
    db "JULIUS V. LANGHOFF"
    db "ANDREAS GRENASBERG"

**Comment by grenasberg** [comment]
Alternativt er å fjerne navna på engelsk script? (selv om vi har jo basert oversettelsen på deres arbeide ...) og bruke tiden vi sparer til å legge inn en ny kategori til slutt:
NORSK VERSJON 2023
The Koholition
Tobias
Julius
Andreas

**Comment by grenasberg** [comment]
"The development team would like to thank you for playing"
Forslag til vår versjon:
"Takk for at du spilte den norske versjonen!"

eventuelt:
"Dedisert til Ea, Bjørn, Finn og Aud"

**Comment by grenasberg** [comment]
hva gjør vi med DAN OWSEN?

**Comment by tobiasvl** [comment]
«The development team»-teksten ligger her: `src/data/credits_3.asm`

**Comment by juliusvl** [comment]
På fransk og tysk er ikke beskjeden skrevet helt ut i grafikken, men kombinerer tegn på tilsynelatende samme måte som i resten av credits. I fransk fil står det "Merci d'avojué", som kan settes sammen til "Merci d'avoir joué". I tysk står det "VielnDakfür'sSp!", som sikkert er "Danke für das Spiel!" eller noe. 
Vi kan jo bare holde det enkelt og si "Takk for at du spilte!" eller som Andreas foreslo, "Takk for at du spilte den norske versjonen!". Eller er det gøy med dedisering?

**Comment by grenasberg** [comment]
Hvis vi skal skrive "Dedisert til Ea, Bjørn, Finn og Aud." må vi ha disse unike bokstavene i /src/gfx/ending/thanks_for_playing.png:
Dedisrt lEa,BjønFogAu.

**Comment by grenasberg** [comment]
her er tegnene vi trenger for å skrive "Takk for at du spilte den norske versjonen!"
Tak fortduspilenovj!
