### ISSUE TITLE
Burn Baby Burn

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#40]

**Comment by grenasberg** [comment]
Vurdere å ha en artig referanse i stedet for bare "La det brenne!" i Dialog094

Dialog094::
    db "Du fikk den     "
    db "magiske staven! "
    db "Nå kan du brenne"
    db "ting! Brenn det!"
    db "La det brenne!@"
;    db "You've got the  "
;    db "Magic Rod!  Now "
;    db "you can burn    "
;    db "things! Burn it!"
;    db "Burn, baby burn!@"

**Comment by grenasberg** [comment]
Ikke så bra forslag til nå:
Håper ikke Hans Olav Brenner vil savne den
Byen e bergen og laget er BRANN!
Du føler allerede en brennende kjærlighet for dette våpenet! (ikke en referanse)
Hus/hotell/slott brenner
Noen må ringe Bjørnis!


...

**Comment by tobiasvl** [comment]
Liker faktisk Bjørnis-forslaget ganske bra. Bjørnis er en fuckings institusjon nå

**Comment by grenasberg** [comment]
Sant. Jeg er med på det hvis det er greit for Julius.

**Comment by juliusvl** [comment]
Jeg har ikke noe forhold til Bjørnis, men hvis det er en stor greie så går vi for det.

**Comment by grenasberg** [comment]
Dialog094::
    db "Du fikk den     "
    db "magiske staven! "
    db "Nå kan du brenne"
    db "ting! Brenn i   "
    db "vei! Noen burde "
    db "kanskje ringe   "
    db "Bjørnis?@"
