### ISSUE TITLE
Jim fra manualen

### ISSUE THREAD

**Issue by juliusvl** [koholition/zelda-links-awakening-NO#41]
Manualen (s. 9) viser hvordan man lager ny fil, og i de originale bildene kalles den nye fila «Jim». Hva skal vår hete?

**Comment by grenasberg** [comment]
Tja
våre navns forbokstaver

**Comment by tobiasvl** [comment]
- Ea
- Bjørn (bra måte å vise fram særnorske bokstaver på)
- Finn
- Aud

**Comment by grenasberg** [comment]
Vi må lage fire versjoner, en for hvert barn. Neida. Men Bjørn er bra det! Han fortjener det så mye som han digger LA.
