### ISSUE TITLE
Vurder og harmoniser egennavn med bindestrek

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#42]

**Comment by grenasberg** [comment]
navn det gjelder:
Koholint-sletta
Tipptopphøydene
Tipptoppfjellene
Ulele-sletta

noen flere?

**Comment by grenasberg** [comment]
research av @juliusvl :
https://www.sprakradet.no/sprakhjelp/Skriveregler/tegn/Bindestrek/
Geografiske og andre navn der førsteleddet sjøl er et egennavn, skal ikke ha bindestrek:
Oslofjorden, Ekofiskfeltet, Krimkrigen, Warszawapakten, Wienkongressen

så vi går for uten bindestrek konsekvent
