### ISSUE TITLE
Fiks fotoalbum-dialog

### ISSUE THREAD

**Issue by juliusvl** [koholition/zelda-links-awakening-NO#44]
Når man går tilbake fra et bilde er den forklarende teksten hardkoda. Vi må finne ut hvor tilemap-et er og bestemme oss for hva som skal stå.

På engelsk er det:
Select A Button
Cancel B Button

**Comment by juliusvl** [comment]
Denne fila inneholder tilesene: [Bilde](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/norwegian/src/gfx/photos/photo_album.png)

**Comment by tobiasvl** [comment]
Hva med:

> Velg: Trykk A
> Avbryt: Trykk B
