### ISSUE TITLE
symbolet for skjell fungerer ikke

### ISSUE THREAD

**Issue by grenasberg** [koholition/zelda-links-awakening-NO#47]
![image](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/6959974/f4c9f40e-a51d-46f9-a9a0-1f7ad5d689d6)
brukes i Dialog1F5
`    db "fikk et skjell <scale>"
`

**Comment by tobiasvl** [comment]
Burde rydde opp i revisions/N0/src/data/ascii_to_tile.asm
