### ISSUE TITLE
Oversette tekst på fotografier og patche inn

### ISSUE THREAD

**Issue by grenasberg** [koholition/zelda-links-awakening-NO#5]
https://legendsoflocalization.com/what-do-those-posters-in-links-awakening-say/ 
https://www.romhacking.net/hacks/2361/

Det blir en spennende utfordring å få inn norsk tekst på like liten plass, særlig på båten.

**Comment by tobiasvl** [comment]
Gennis at den engelske oversettelsen av plakatene byttet om på dem!

**Comment by tobiasvl** [comment]
@juliusvl får hovedansvar for denne siden han kan lage pikselgrafikk, men bare deleger oversettelse

**Comment by grenasberg** [comment]
hvordan kan vi finne ut hvilke tiles(?) det er som inneholder teksten og dermed hvor mye/lite plass vi har til norsk tekst?

**Comment by tobiasvl** [comment]
https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/photos/photo_shop.png

**Comment by grenasberg** [comment]
https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/photos/photo_fisherman.png og denne

**Comment by grenasberg** [comment]
skulle ikke lukke 😳

**Comment by grenasberg** [comment]
https://www.batmagasinet.no/norges-ti-mest-populaere-batnavn/167195
må finne navn på båten.

**Comment by juliusvl** [comment]
Kan jo hete «Stor fangst» eller noe á là det den heter på japansk da. Eller skal vi finne på noe nytt? Inside joke/easter egg kanskje?

**Comment by tobiasvl** [comment]
Synes ikke vi skal oversette det ordrett nei.

Hva med "Mary", som en referanse til Rasmus Klump? Hehe nei da

Helge Ingstad?

**Comment by juliusvl** [comment]
MEMO til meg/alle: Print-grafikken må også oversettes i grafikk

**Comment by tobiasvl** [comment]
> MEMO til meg/alle: Print-grafikken må også oversettes i grafikk

Ja, se også #9
