### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by juliusvl** [koholition/zelda-links-awakening-NO#50]
Denne må leses korrektur på! 

[Booklet korrektur.pdf](https://github.com/tobiasvl/zelda-links-awakening-NO/files/13403475/Booklet.korrektur.pdf)

Ellers må jeg fikse disse tinga:
- [ ] Fargekorrigere alle bilder av Link
- [x] Fikse pikselerte konturstreker på noen objekter (f.eks fangehullnøklene, krystallkule, krukke)

**Comment by grenasberg** [comment]
husker ikke om vi har snakket om det før og kommet fram til karakter, men jeg tror jeg heller mot å kalle det "Figurgalleri" på side 27 og "Du kommer til å møte mange andre figurer" på side 28. 

ellers tror jeg denne er gucci

**Comment by tobiasvl** [comment]
* Skal «Hyrulianske» ha stor H? Vi sier jo ikke «Norske» eller «Engelske»
* På side 13 mangler det et punktum etter «Trykk på B-knappen for å avbryte en melding»
* «Hvis du løper inn i en vegg med pegasusstøvlene kan du kanskje lage et hull i den.» - Det kan du vel aldri
* Medisinen kalles både medisin og vidundermiddel i manualen
* Side 27: «virker til å være» høres rart ut, kan man si det? Hva med bare «virker å være»?
