### ISSUE TITLE
Eske

### ISSUE THREAD

**Issue by juliusvl** [koholition/zelda-links-awakening-NO#51]
Her er så langt arbeidet med esken har kommet. 
Les gjerne korrektur og kom med forslag til endringer hvis dere syns noe skal endres.

Skal vi ha med noe á là dette?
<img width="399" alt="image" src="https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/2b10bff4-12fd-48c0-a9a1-821e4099e373">

![eske3](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/180a40a5-22b4-465c-b5d2-39121d9a82e0)

**Comment by grenasberg** [comment]
Resirk: Denne pappen er 100% gjenbrukt frokostblandingboks med påklistra nyprint.

**Comment by grenasberg** [comment]
valuable limited warranty etc:
EKSTREMT BEGRENSET OPPLAG
RING 815 493 00 FOR MER INFORMASJON

IKKE TIL SALGS NOEN STEDER, MEN DU KAN PATCHE ROM OG PRINTE DIN EGEN ESKE HVIS DU VIL

**Comment by grenasberg** [comment]
Én skapning, en snakkende ugle, _kjenner kanskje løsningen til Links dilemma._
var litt svak setning. engelskaktig. og hvilket dilemma egentlig? eller er det jeg som er tett i nøtta? 
hva med
Én skapning, en snakkende ugle, _vet muligens hvor Links ferd må gå._

ellers er teksten god!

**Comment by juliusvl** [comment]
Gode innspill! Hvis @tobiasvl er enig gjør jeg den ferdig asap.

Skal vi ha noe gøy gjemt i strekkoden?

**Comment by juliusvl** [comment]
Forslag: 
<img width="1444" alt="image" src="https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/88c8f6cb-4dca-4cbf-bd38-02ef5e81e6ff">

**Comment by juliusvl** [comment]
Hvis noen har forslag til easter egg i strekkoden hadde det vært gøy! Eventuelt QR-kode som lenker til patche-siden?

**Comment by tobiasvl** [comment]
QR til patchesiden er jo fett

**Comment by grenasberg** [comment]
ja, god ide
