### ISSUE TITLE
Tittelskjerm

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#7]
Forslag fra @juliusvl:

![image](https://user-images.githubusercontent.com/80824/195082421-d71ac506-61ae-4248-bef4-6aeb079c75c7.png)

**Comment by juliusvl** [comment]
Denne kan closes, eller?

**Comment by tobiasvl** [comment]
Kan vel det, må fortsatt finne et navn på gruppa vår da

**Comment by tobiasvl** [comment]
The Koholition

**Comment by juliusvl** [comment]
![image](https://user-images.githubusercontent.com/16557480/227730628-32445787-1ff6-4121-9a1e-0a8b05c0b6d4.png)

**Comment by juliusvl** [comment]
![image](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/19c78070-8985-4efb-92d0-677ccb776ea9)
Tittelskjerm med Koholition
