### ISSUE TITLE
Oversett grafikk med tekst

### ISSUE THREAD

**Issue by tobiasvl** [koholition/zelda-links-awakening-NO#9]
Som #5, bare at det må oversettes fra engelsk. Merk at spillet bruker ofte forskjellige tiles basert på om det spilles på DMG eller CGB, så det må endres to steder.

- [x] Player select: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/menus/menu.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/menus/menu.cgb.png)
- [x] Your name?
- [x] PUSH SELECT og WEAR: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/norwegian/src/gfx/characters/oam_color_dungeon.png)
- [x] Sletting
- [x] Kopiering
- [x] [Print](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/menus/print.png)
- [x] Christine: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/scenes/christine.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/scenes/christine.cgb.png)
- [x] Shop: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/world/overworld_1.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/world/overworld_1.cgb.png)
- [x] Shop, raft, camera: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/world/overworld_2.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/world/overworld_2.cgb.png)
- [x] Game Over: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/menus/save_menu.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/menus/save_menu.cgb.png)
- [x] ~~Ending (det står «player» her, vet ikke hva det brukes til): [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/ending/ending_1.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/ending/ending_1.cgb.png)~~ Brukes ikke
- [x] [Thanks for playing](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/ending/thanks_for_playing.png) #33 
- [x] ~~Etasjer i dungeon map: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/items/minimap_dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/items/minimap_cgb.png) - Hva betyr B-en? - Basement~~ Trengs ikke fordi det ikke vises i DX
- [x] Æ Ø Å i stor font brukt i rulletekst: [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/fonts/font_large.dmg.png), [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/fonts/font_large.cgb.png), [credits](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/main/src/gfx/ending/credits_roll.png)
- [x] Save & Quit
- [x] Fotoalbum-tekst #44 
- [x] OH! I Mons' sang [CGB](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/norwegian/src/gfx/characters/oam_npc_3.cgb.png) [DMG](https://github.com/tobiasvl/zelda-links-awakening-NO/blob/norwegian/src/gfx/characters/oam_npc_3.dmg.png)

**Comment by juliusvl** [comment]
<img width="928" alt="image" src="https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/1fad2371-827b-4d2e-90c0-d1cb4c0fafe6">
Guide til utskriftsdialoger

**Comment by juliusvl** [comment]
![print_ui_1](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/a35c972e-c2dd-4fc3-9484-4c7a26d4e088)
Dette er riktig versjon av fila der «JA» er lagt riktig.

**Comment by juliusvl** [comment]
Vi må huske å redigere PRINTING-teksten der VOVVOV drar teksten og den animeres.

**Comment by tobiasvl** [comment]
PRINTING-teksten der VOVVOV drar teksten og den animeres: `revisions/N0/src/data/photo_album/print_animation.asm`

**Comment by tobiasvl** [comment]
Etasjer i dungeon map: B -> U? (B betyr vel «basement», føler U brukes mest på norsk for «underetasje»)

**Comment by juliusvl** [comment]
Det er logisk, men gikk vi ikke vekk fra dette? Det er vel bare én fangekjeller dette er aktuelt, hvis kartet over Nøkkelkjelleren skal samles til én etasje som i originalen? Eller husker jeg feil her

**Comment by juliusvl** [comment]
"OH!" I Mons' sang: Skal vi skrive "Å!" eller "ÅH!"? Eller eventuelt noe annet som kan passe på så liten plass?
